import { Product, Category } from './types'

export const categories: Category[] = [
  { id: '1', name: 'Fresh Produce',   slug: 'produce',   icon: '🥦', color: 'bg-green-100 text-green-800' },
  { id: '2', name: 'Meat & Seafood',  slug: 'meat',      icon: '🥩', color: 'bg-red-100 text-red-800' },
  { id: '3', name: 'Dairy & Eggs',    slug: 'dairy',     icon: '🥛', color: 'bg-blue-100 text-blue-800' },
  { id: '4', name: 'Bakery',          slug: 'bakery',    icon: '🍞', color: 'bg-amber-100 text-amber-800' },
  { id: '5', name: 'Frozen Foods',    slug: 'frozen',    icon: '❄️',  color: 'bg-sky-100 text-sky-800' },
  { id: '6', name: 'Pantry',          slug: 'pantry',    icon: '🥫', color: 'bg-orange-100 text-orange-800' },
  { id: '7', name: 'Beverages',       slug: 'beverages', icon: '🧃', color: 'bg-purple-100 text-purple-800' },
  { id: '8', name: 'Snacks',          slug: 'snacks',    icon: '🍿', color: 'bg-yellow-100 text-yellow-800' },
  { id: '9', name: 'Household',       slug: 'household', icon: '🧹', color: 'bg-teal-100 text-teal-800' },
  { id: '10', name: 'Personal Care',  slug: 'personal',  icon: '🧴', color: 'bg-pink-100 text-pink-800' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Baby Spinach',
    slug: 'organic-baby-spinach',
    description: 'Tender, pre-washed organic baby spinach leaves. Perfect for salads, smoothies, and sautés.',
    price: 3.99,
    comparePrice: 5.49,
    unit: '5 oz bag',
    category: 'produce',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.8,
    reviewCount: 342,
    tags: ['organic', 'leafy-greens', 'salad'],
    isOrganic: true,
    isSale: true,
    brand: 'Earthbound Farm',
  },
  {
    id: '2',
    name: 'Fresh Atlantic Salmon',
    slug: 'fresh-atlantic-salmon',
    description: 'Farm-raised Atlantic salmon fillets. Rich in omega-3 fatty acids. Skin-on, boneless.',
    price: 12.99,
    unit: 'per lb',
    category: 'meat',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.7,
    reviewCount: 218,
    tags: ['seafood', 'fish', 'omega-3'],
    brand: "Busters' Fresh Market",
  },
  {
    id: '3',
    name: 'Free-Range Brown Eggs',
    slug: 'free-range-brown-eggs',
    description: 'Grade A large brown eggs from free-range hens. Hormone and antibiotic free.',
    price: 5.49,
    comparePrice: 6.99,
    unit: 'dozen',
    category: 'dairy',
    image: 'https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.9,
    reviewCount: 891,
    tags: ['eggs', 'free-range', 'breakfast'],
    isSale: true,
    brand: 'Happy Hens',
  },
  {
    id: '4',
    name: 'Artisan Sourdough Boule',
    slug: 'artisan-sourdough-boule',
    description: 'Freshly baked sourdough boule with a crispy crust and chewy interior. Baked in-store daily.',
    price: 6.99,
    unit: 'whole loaf',
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.9,
    reviewCount: 457,
    tags: ['bread', 'sourdough', 'artisan', 'fresh-baked'],
    isNew: true,
    brand: "Buster's Bakehouse",
  },
  {
    id: '5',
    name: 'Organic Whole Milk',
    slug: 'organic-whole-milk',
    description: 'Certified organic whole milk from pasture-raised cows. No rBST hormones.',
    price: 7.29,
    unit: 'half gallon',
    category: 'dairy',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.7,
    reviewCount: 563,
    tags: ['milk', 'organic', 'dairy'],
    isOrganic: true,
    brand: 'Organic Valley',
  },
  {
    id: '6',
    name: 'Hass Avocados',
    slug: 'hass-avocados',
    description: 'Perfectly ripe Hass avocados with creamy texture. Ready to eat today.',
    price: 1.49,
    unit: 'each',
    category: 'produce',
    image: 'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.6,
    reviewCount: 712,
    tags: ['avocado', 'fruit', 'healthy-fat'],
  },
  {
    id: '7',
    name: 'Ground Beef 80/20',
    slug: 'ground-beef-80-20',
    description: 'Premium ground beef, 80% lean 20% fat blend. Perfect for burgers and meatballs.',
    price: 6.99,
    unit: 'per lb',
    category: 'meat',
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.8,
    reviewCount: 334,
    tags: ['beef', 'ground', 'burgers'],
    brand: 'Busters Butcher',
  },
  {
    id: '8',
    name: 'Organic Blueberries',
    slug: 'organic-blueberries',
    description: 'Plump, sweet organic blueberries. Packed with antioxidants. Perfect for snacking or baking.',
    price: 4.99,
    comparePrice: 6.99,
    unit: 'pint',
    category: 'produce',
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.9,
    reviewCount: 1204,
    tags: ['berries', 'organic', 'antioxidants'],
    isOrganic: true,
    isSale: true,
  },
  {
    id: '9',
    name: 'Sharp Cheddar Cheese',
    slug: 'sharp-cheddar-cheese',
    description: 'Aged Vermont sharp cheddar. Bold, tangy flavor. Great for sandwiches, charcuterie, and cooking.',
    price: 8.49,
    unit: '16 oz block',
    category: 'dairy',
    image: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.7,
    reviewCount: 289,
    tags: ['cheese', 'cheddar', 'dairy'],
    brand: 'Cabot Creamery',
  },
  {
    id: '10',
    name: 'Russet Potatoes',
    slug: 'russet-potatoes',
    description: 'Idaho russet potatoes. Ideal for baking, mashing, and frying. Grown locally.',
    price: 4.99,
    unit: '5 lb bag',
    category: 'produce',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.5,
    reviewCount: 445,
    tags: ['potatoes', 'vegetables', 'starchy'],
    isNew: false,
  },
  {
    id: '11',
    name: 'Almond Milk Unsweetened',
    slug: 'almond-milk-unsweetened',
    description: 'Creamy, unsweetened almond milk. Dairy-free, vegan, and low calorie. Fortified with Vitamins D & E.',
    price: 4.29,
    comparePrice: 5.49,
    unit: 'half gallon',
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1600718374662-0483d2b9da44?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.6,
    reviewCount: 678,
    tags: ['almond-milk', 'dairy-free', 'vegan'],
    isSale: true,
    brand: 'Califia Farms',
  },
  {
    id: '12',
    name: 'Chicken Breast Boneless',
    slug: 'chicken-breast-boneless',
    description: 'All-natural boneless skinless chicken breasts. No antibiotics ever. Air-chilled for better flavor.',
    price: 7.99,
    unit: 'per lb',
    category: 'meat',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
    inStock: true,
    rating: 4.8,
    reviewCount: 927,
    tags: ['chicken', 'poultry', 'protein'],
    brand: 'Bell & Evans',
  },
]

export const weeklyDeals = products.filter(p => p.isSale)
export const featuredProducts = products.slice(0, 8)
export const newArrivals = products.filter(p => p.isNew)
